Filter abilities
orichalque/yet-an-other-gloomhaven-companion pull request #189
Opened 2021-12-20 13:12 UTC by orichalque

2021-12-20 13:13 UTC, orichalque commented
- Normalized database
- Added filter button

2021-12-20 18:06 UTC, RaphaelPage0110 commented on index.html
> +                    <img v-bind:src="'data/'+cprd.image" style="width:8em" class="image rounded" />
This looks like a typo

2021-12-20 18:09 UTC, RaphaelPage0110 requested changes
Looks good, there just seems to be typo in index.html line 517

2021-12-20 18:15 UTC, RaphaelPage0110 commented
![image](https://user-images.githubusercontent.com/26387222/146813535-412972f6-eb19-46e8-816b-ab572c7a33f0.png)
Is there a way to not have the extra border here? (that's in the ability page)
The filter 'button' is not very pretty either. Maybe just a text would be better, to match the 'Character Level' label?

2021-12-20 18:18 UTC, RaphaelPage0110 commented
There is a bug on the Gear tab. Steps to reproduce : 
1) Go to the gear tab
2) Click on the 1-14 card back
Expected : the gears 1 to 14 shows
Actual : No gear is shown

I suspect it's because the filter is empty?

2021-12-21 19:50 UTC, RaphaelPage0110 approved these changes

2021-12-22 07:56 UTC, merged