[206] Import Export
orichalque/yet-an-other-gloomhaven-companion pull request #208
Opened 2022-01-11 15:09 UTC by orichalque

#206

2022-01-11 15:10 UTC, orichalque commented
@RaphaelPage0110 not sure that the import / export buttons are well positioned though. 
Should we put it in a common dropdown menu with the Save button ? I think the save button should remain quick to use so I dont think so :s 
Wdyt ?

2022-01-12 15:18 UTC, RaphaelPage0110 commented
> @RaphaelPage0110 not sure that the import / export buttons are well positioned though. Should we put it in a common dropdown menu with the Save button ? I think the save button should remain quick to use so I dont think so :s Wdyt ?
> 
> Maybe it could be in a dropdown submenu along with the "Save gameplay" data option ?
> 
> ATM: ![image](https://user-images.githubusercontent.com/6909730/148968682-1bf972fd-a6cc-45ef-a7fe-2d2fd65f1cff.png)
> 
> Proposition 1: ![image](https://user-images.githubusercontent.com/6909730/148975134-e0d11a77-14c2-498d-8eed-150db9b3b942.png)

I agree, I don't think putting it in the About section is a good idea.  Your proposition 1 seems good. The only concern I have is that the Options submenu is becoming quite large. But I think it's ok for now!

2022-01-12 15:27 UTC, RaphaelPage0110 requested changes
- The name of the export file is currently just 'save.json'. Maybe you could name it something a little bit more explicit like "gloomhaven_deckbuilder_export" or something?
- The special modifiers are not exported. Is that normal?

Very good job otherwise, this is awesome!

2022-01-12 15:27 UTC, RaphaelPage0110 commented on js/main.js
> +            //const text = await file.text();
you can probably remove this

2022-01-12 15:28 UTC, RaphaelPage0110 commented
> **A reviewer left a comment:**
> 
> Export wont work if no class is selected; That's pretty obvious, but I suppose a red dialog should be opened to log this event.
> Browser metadata
> 
> [Open Deploy Preview](https://deploy-preview-208--gloomhaven-dev.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61dd9d94c91e83000773c56e&commentID=61ded4e9a0f5b7218e1eb23a&resolution=resolved)

Good idea too

2022-01-12 15:41 UTC, orichalque commented on js/main.js
> +            //const text = await file.text();
yup

2022-01-12 15:41 UTC, orichalque commented
> * The name of the export file is currently just 'save.json'. Maybe you could name it something a little bit more explicit like "gloomhaven_deckbuilder_export" or something?

Good point, will do 

> * The special modifiers are not exported. Is that normal?

No it's not. I'm checking this out

2022-01-13 18:08 UTC, RaphaelPage0110 commented
I have the following error in the console when importing data : 
![image](https://user-images.githubusercontent.com/26387222/149385278-ad71107f-673a-442b-b0ad-31fec3fda524.png)

2022-01-13 18:09 UTC, RaphaelPage0110 commented
Also the file name is still save.json :)

2022-01-14 05:58 UTC, orichalque commented
> Also the file name is still save.json :)

yeah thats because im not done with these changes

2022-01-20 07:26 UTC, RaphaelPage0110 approved these changes

2022-01-20 07:27 UTC, RaphaelPage0110 commented
It's perfect! You can merge it if you are done :)

2022-01-20 07:59 UTC, merged